import { gql, useQuery } from '@apollo/client';
import { Box } from '@chakra-ui/react';
import type { NextPage } from 'next'
import Head from 'next/head'
import { ChangeEvent, useEffect, useState } from 'react';
import { FilterBar } from '../components/FilterBar';
import { MissionList } from '../components/MissionList.tsx'
import styles from '../assets/styles/Home.module.css';


interface Mission {
  description: string;
  id: string;
  manufacturers: string[];
  twitter: string;
  website: string;
  wikipedia: string;
  name: string;
}

interface GetMissionsData {
  missions: Mission[];
}

interface GetMissionsVars {
  limit: number;
  name: string;
}

const GET_MISSIONS = gql`
  query GetMissions($limit: Int!, $name: String!) {
    missions(limit: $limit, find: { name:  $name }) {
      description
      id
      manufacturers
      twitter
      website
      wikipedia
      name
    }
  }
  
`;

const Home: NextPage = () => {
  const [filter, setFilter] = useState('');

  const { loading, data } = useQuery<GetMissionsData, GetMissionsVars>(
    GET_MISSIONS,
    { variables: { limit: 10, name: filter } }
  )

  const handleFilterChange = (filterValue: string) => {
    setFilter(filterValue)
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>SpaceX Mission List</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box mb="3">
        <FilterBar onFilterChange={handleFilterChange} />
      </Box>

      {!loading &&<MissionList missionList={data!.missions} />}
    </div>
  )
}

export default Home
